#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"
env_files = []

[build]
    cmd = "go build -o ./tmp/main ./main.go"

  # Binary path ONLY (no arguments here)
  bin = "./tmp/main"

  # Arguments passed to your Go binary on execution
  args_bin = ["server"]

  delay = 1000

  # Added "templ" so Air notices Templ file modifications
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]

  exclude_dir = [
    "assets",
    "tmp",
    "html",
    "vendor",
    "testdata",
    "node_modules",
    "internals/server/assets/static"
  ]
  exclude_file = []
  exclude_regex = ["_test.go"]

  kill_delay = "0s"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
  log = "build-errors.log"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  silent = false
  time = false
  main_only = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true
  proxy_port = 20000
  app_port = 8080      # Make sure your Go server listens on port 8080!
  app_start_timeout = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true